<!DOCTYPE html>
<html lang="cs-cz">
        <head>
                <base href="/localhost" />
                <meta charset="UTF-8" />
                <title><?= $titulek ?></title>
                <meta name="description" content="<?= $popis ?>" />
                <meta name="keywords" content="<?= $klicova_slova ?>" />
                <link rel="stylesheet" href="style.css" type="text/css"/>
        </head>

        <body>
                <header>
                        <h1>Elektronická evidence kosmonautů</h1>
                </header>
            <?php foreach ($zpravy as $zprava) : ?>
            <p class="zprava"><?= $zprava ?></p>
            <?php endforeach ?>
                <nav>
                        <ul>                                     
                                <li><a href="kosmonaut">Přehled</a></li>
                                <li><a href="administrace">Administrace</a>
                        </ul>
                </nav>
                <br clear="both" />

                <article>
                        <?php $this->kontroler->vypisPohled(); ?>
                </article>

                <footer>
                        <p>Elektronická evidence založená na MVC architektuře
                        <a href="http://www.itnetwork.cz" target="_blank">itnetwork.cz</a>.</p>
                        <a href="administrace">Administrace</a>
                </footer>
        </body>
</html>
